### ISSUE TITLE
creating closure inside async leads to loosing its context

### ISSUE THREAD

**Issue by blackmius** [yglukhov/yasync#1]
Found that closures cannot be created inside async function
```nim
import yasync

proc callSoon(cb: proc ()) =
  cb()

proc f(a: int) {.async.} =
  callSoon do:
    echo a
```
this code will output this error
```
Error: internal error: inconsistent environment type
```

why i am ever want to create closures inside async procs? I want to make callSoon after doing some async stuff. for example schedule flushing after receiving data and writing it to a buffer

**Comment by yglukhov** [comment]
Yes, that is an inherent limitation of yasync. In your example `a` parameter becomes part of the `f` environment. Since async environments are not guaranteed to be heap-allocated like usual nim closure environments, you can not safely capture anything from such environment into a closure. 

As a workaround, you can use `asyncClosureExperimental` pragma instead of `yasync` pragma. It will make it work akin to how std/asyncdispatch works, and as such closures will be working as normal, but of course, you'll be missing out on yasync closure-env-optimization for such functions.
