### ISSUE TITLE
Improve compatibility with asyncdispatch

### ISSUE THREAD

**Issue by nitely** [yglukhov/yasync#5]
Ideally, importing yasync + yasync/compat would just make my asyncdispatch code work. This way I could just add a `when` condition based on some flag and import one lib or the other.

Not sure how that would look like, but probably things like `asyncCheck` would be a no-op, and returning `Future[T]` or just `T` would be both supported. You probably want to keep `awaitc` to make awaits on asyncdispatch explicit, but then it would need to be an alias for `await` when not importing yasync...

As an aside I tried yasync on hyperx and got a 2x speed up which is great! but as you can see [here it requires a bunch of changes](https://github.com/nitely/nim-hyperx/compare/master...futurevar).

**Comment by yglukhov** [comment]
Hey, thanks for your feedback. My goal for `yasync/compat` was not to provide a drop-in replacement, but to allow integration between yasync and asyncdispatch code. There are some small "syntactic" decisions in yasync which are different from asyncdispatch, (like using T instead of Future[T], lack of asyncCheck, etc), which I'm not willing to give up on them, call me opinionated :). In particular I find `asyncCheck` harmful with its error handling, and instead the following pattern should be used: `myAsyncProc().then do(e: ref Exception): ...`. `awaitc` I would have gladly replaced with just an overloaded `await`, but unfortunately there's a [nim bug](https://github.com/nim-lang/Nim/issues/20100) preventing me from doing that.

> As an aside I tried yasync on hyperx and got a 2x speed up which is great!

That is great to hear! Last time I tried benchmarking, I could not come up with a good benchmark :)

> but as you can see [here it requires a bunch of changes](https://github.com/nitely/nim-hyperx/compare/master...futurevar).

Well yes, these changes look totally legit to me, and I hope you find your code looks better with them, like I do :)

Hope you find my reasoning fair.

**Comment by nitely** [comment]
I think proving a drop-in replacement would be a way to increase adoption. Everything in my comment can be done outside of yasync anyway, for example an async macro that adds the Future[T] back and then calling yasync async macro, etc. Although, maybe a better way is a nimble package that provides a drop-in replacement for every async implementation.

Anyway, the current yasync state is very useful as it's. Thanks for creating it.

**Comment by yglukhov** [comment]
> maybe a better way is a nimble package

Absolutely! It's just I don't want to take the burden of maintaining this glue, I'd rather focus on developing yasync further instead.
